name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Base stats
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: froozeify
          template: classic
          config_timezone: Europe/Paris
          filename: metrics-base.svg
          base: header, community, repositories, metadata

      # Languages
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: froozeify
          template: classic
          config_timezone: Europe/Paris
          filename: metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      # Isometric calendar
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: froozeify
          template: classic
          config_timezone: Europe/Paris
          filename: metrics-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # Recent activity
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: froozeify
          template: classic
          config_timezone: Europe/Paris
          filename: metrics-activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public

      # Achievements
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: froozeify
          template: classic
          config_timezone: Europe/Paris
          filename: metrics-achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

      # Topics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: froozeify
          template: classic
          config_timezone: Europe/Paris
          filename: metrics-topics.svg
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
